<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup Label="Package References">
    <PackageReference Include="ppy.osu.Framework" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources/**/*" />
  </ItemGroup>
  <ItemGroup Label="README">
    <None Include="$(MSBuildThisFileDirectory)\..\.github\README.nuget.md" Visible="false">
      <Pack>True</Pack>
      <PackagePath>README.md</PackagePath>
    </None>
  </ItemGroup>
</Project>
